#
# FS Loox Makefile for the linux kernel.
#
obj-$(CONFIG_MACH_LOOX720)	+= loox720.o
obj-$(CONFIG_MACH_LOOX720)      += loox720_rfkill.o
obj-$(CONFIG_MACH_LOOX720)      += loox720_leds.o
obj-$(CONFIG_PM)		+= loox720_pm.o
#obj-$(CONFIG_LOOX720_TS)		+= loox720_ts.o
#obj-$(CONFIG_LOOX720_ADS7846)		+= loox720_spi_ads7846.o

