name: Build Platform
inputs:
  codename:
    description: “Platform codename”
    required: true

runs:
  using: "composite"
  steps:
  - name: make ${{inputs.registry_username}}_defconfig
    run: make ${{inputs.registry_username}}_defconfig
    env:
      CROSS_COMPILE: ./gcc-arm-none-eabi-4_8-2014q2/bin/arm-none-eabi-

  - name: make zImage
    run: make zImage -j2
    env:
      CROSS_COMPILE: ./gcc-arm-none-eabi-4_8-2014q2/bin/arm-none-eabi-

  - name: make modules
    run: make modules -j2
    env:
      CROSS_COMPILE: ./gcc-arm-none-eabi-4_8-2014q2/bin/arm-none-eabi-

  - name: make modules_install
    run: make INSTALL_MOD_PATH=./modules -j2 modules_install
    env:
      CROSS_COMPILE: ./gcc-arm-none-eabi-4_8-2014q2/bin/arm-none-eabi-

  - name: Pack modules to tar
    run: sudo tar --create --ignore-failed-read --preserve-permissions --recursion --sparse --totals --wildcards --gzip --file=modules.tar.gz ./modules/*

  - name: Move kernel and modules to output
    run: mv ./arch/arm/boot/zImage ./output/${{inputs.registry_username}}-zImage; mv modules.tar.gz ./output/${{inputs.registry_username}}-modules.tar.gz;

  - name: Clean
    run: rm -r ./modules
